### ISSUE TITLE
Thank you I need more info

### ISSUE THREAD

**Issue by elly3559** [Metalnem/hkpropel-downloader#1]
Hi Thank you,

Thank you for creating this and the blog. I do alright in finding the books I need. However, HKpropel has been one hella struggle. Can I have the instructions on how to use this code? 
I was devastated when I couldn't download it from their platform I would have just got it from somewhere else that was easier to use and download from. 

Cheers 
Elly

**Comment by Metalnem** [comment]
Hi @elly3559!

Here is how you can use the code:

1. Download and install the .NET SDK (https://dotnet.microsoft.com/en-us/download).
2. Open the book in the HKPropel portal.
3. Open developer tools in your browser and refresh the page.
4. In the `Network` tab, find the `package.opf` request.
5. Find the request URL and strip everything after the /OPS/ part. The end result will look something like https://hkpropel-mbx-cloud.humankinetics.com/content/secure/123/45678/abc12345def/OPS/.
6. Find the request cookie.
7. Put the URL into HKPROPEL_URL environment variable.
8. Put the cookie into HKPROPEL_COOKIE environment variable.
9. Run the code with the following command `dotnet run`.
10. Wait until the program completes. The result will be your ebook in ePub format.
